name: React-S3-Test CD (Continuos Deploy)

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/react-s3-experiment:latest

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .envfor CD
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx create --name builder --use
          docker buildx build --platform linux/amd64,kinux/arm64 \
            -t ${{ env.DOCKER_IMAGE }} --push .
          docker logout

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: [ self-hosted, deploy-s3-frontend ]
    steps:
      - name: Deploy to Production
        run: |
          echo "ready for deploy"

          cd /home/ec2-user/s3-experiment/react
          docker-compose down

          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ${{ env.DOCKER_IMAG }}

          docker image prune -f
          docker logout

          docker-compose up -d

          

      
          
